# Generated by Django 5.1.4 on 2025-01-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_allocator_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Technology',
        ),
        migrations.AddField(
            model_name='project',
            name='Technologies',
            field=models.ManyToManyField(related_name='projects', to='dev_allocator_app.technology'),
        ),
    ]
